"""Export crontab jobs to systemd timer + service units."""

import re
from pathlib import Path
from typing import Optional

from .repo import get_module_path, list_modules


_VAR_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)")
_SPECIAL_RE = re.compile(r"^(@\w+)\s+(.*)")
_SHELL_META = re.compile(r"[;&|<>`]|\$\(|&&|\|\|")

_SPECIAL_CALENDAR = {
    "@hourly": "hourly",
    "@daily": "daily",
    "@midnight": "daily",
    "@weekly": "weekly",
    "@monthly": "monthly",
    "@yearly": "yearly",
    "@annually": "yearly",
}

_DOW = {
    "0": "Sun",
    "7": "Sun",
    "1": "Mon",
    "2": "Tue",
    "3": "Wed",
    "4": "Thu",
    "5": "Fri",
    "6": "Sat",
}


# ---------------------------------------------------------------------------
# Cron → OnCalendar conversion
# ---------------------------------------------------------------------------


def _map_dow(token: str) -> str:
    return _DOW.get(token, token.capitalize())


def _convert_field(
    f: str, start: int = 0, is_dow: bool = False, pad: bool = False
) -> str:
    """Convert one cron field to the equivalent systemd OnCalendar token."""
    if f == "*":
        return "*"
    if f.startswith("*/"):
        n = f[2:]
        return f"{start}/{n}"
    if "," in f:
        parts = f.split(",")
        if is_dow:
            parts = [_map_dow(p) for p in parts]
        elif pad:
            parts = [p.zfill(2) for p in parts]
        return ",".join(parts)
    if "-" in f:
        a, b = f.split("-", 1)
        if is_dow:
            return f"{_map_dow(a)}..{_map_dow(b)}"
        if pad:
            return f"{a.zfill(2)}..{b.zfill(2)}"
        return f"{a}..{b}"
    if is_dow:
        return _map_dow(f)
    return f.zfill(2) if pad and f.isdigit() else f


def _cron_to_oncalendar(fields: list[str]) -> str:
    """Convert 5 cron fields to a systemd OnCalendar expression."""
    mn, hr, dom, mon, dow = fields

    dow_prefix = ""
    if dow != "*":
        dow_prefix = _convert_field(dow, is_dow=True) + " "

    date = f"*-{_convert_field(mon, start=1, pad=True)}-{_convert_field(dom, start=1, pad=True)}"
    time = f"{_convert_field(hr, start=0, pad=True)}:{_convert_field(mn, start=0, pad=True)}:00"

    return f"{dow_prefix}{date} {time}"


# ---------------------------------------------------------------------------
# Unit name derivation
# ---------------------------------------------------------------------------


def _unit_name(cmd: str, seen: set[str]) -> str:
    exe = Path(cmd.split()[0]).stem if cmd.split() else "job"
    base = re.sub(r"[^a-zA-Z0-9-]", "-", exe).strip("-") or "job"
    name = f"vicron-{base}"
    if name not in seen:
        seen.add(name)
        return name
    i = 2
    while f"{name}-{i}" in seen:
        i += 1
    name = f"{name}-{i}"
    seen.add(name)
    return name


# ---------------------------------------------------------------------------
# Unit file rendering
# ---------------------------------------------------------------------------


def _exec_start(cmd: str) -> str:
    """Wrap command in sh -c if it contains shell metacharacters."""
    if _SHELL_META.search(cmd):
        escaped = cmd.replace("'", "'\\''")
        return f"/bin/sh -c '{escaped}'"
    return cmd


def _service(unit_name: str, cmd: str, module: str) -> str:
    return (
        f"# generated by vicron from module: {module}\n"
        f"[Unit]\n"
        f"Description=vicron: {cmd}\n"
        f"\n"
        f"[Service]\n"
        f"Type=oneshot\n"
        f"ExecStart={_exec_start(cmd)}\n"
    )


def _timer(unit_name: str, calendar: str) -> str:
    return (
        f"[Unit]\n"
        f"Description=vicron timer: {unit_name}\n"
        f"\n"
        f"[Timer]\n"
        f"OnCalendar={calendar}\n"
        f"Persistent=true\n"
        f"\n"
        f"[Install]\n"
        f"WantedBy=timers.target\n"
    )


def _reboot_service(unit_name: str, cmd: str, module: str) -> str:
    return (
        f"# generated by vicron from module: {module}\n"
        f"# @reboot has no timer equivalent — install as a one-shot service\n"
        f"[Unit]\n"
        f"Description=vicron @reboot: {cmd}\n"
        f"After=network.target\n"
        f"\n"
        f"[Service]\n"
        f"Type=oneshot\n"
        f"ExecStart={_exec_start(cmd)}\n"
        f"RemainAfterExit=yes\n"
        f"\n"
        f"[Install]\n"
        f"WantedBy=multi-user.target\n"
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


class ExportedUnit:
    def __init__(
        self, name: str, service: str, timer: Optional[str], reboot: bool = False
    ):
        self.name = name
        self.service = service
        self.timer = timer
        self.reboot = reboot  # @reboot jobs: service only, no timer


def generate(output_dir: Optional[Path] = None) -> list[ExportedUnit]:
    """
    Generate systemd units for all active cron jobs.
    If output_dir is given, writes .service/.timer files there.
    """
    units: list[ExportedUnit] = []
    seen_names: set[str] = set()

    for module_name in list_modules():
        content = get_module_path(module_name).read_text()
        for line in content.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if _VAR_RE.match(stripped):
                continue

            # @special
            m = _SPECIAL_RE.match(stripped)
            if m:
                special, cmd = m.group(1).lower(), m.group(2)
                name = _unit_name(cmd, seen_names)
                if special == "@reboot":
                    units.append(
                        ExportedUnit(
                            name,
                            _reboot_service(name, cmd, module_name),
                            timer=None,
                            reboot=True,
                        )
                    )
                else:
                    calendar = _SPECIAL_CALENDAR.get(special, "daily")
                    units.append(
                        ExportedUnit(
                            name,
                            _service(name, cmd, module_name),
                            _timer(name, calendar),
                        )
                    )
                continue

            # Standard 5-field entry
            parts = stripped.split(None, 5)
            if len(parts) < 6:
                continue
            cmd = parts[5]
            calendar = _cron_to_oncalendar(parts[:5])
            name = _unit_name(cmd, seen_names)
            units.append(
                ExportedUnit(
                    name,
                    _service(name, cmd, module_name),
                    _timer(name, calendar),
                )
            )

    if output_dir is not None:
        output_dir.mkdir(parents=True, exist_ok=True)
        for u in units:
            (output_dir / f"{u.name}.service").write_text(u.service)
            if u.timer:
                (output_dir / f"{u.name}.timer").write_text(u.timer)

    return units
